title: "Oktrik"
email: info@oktrik.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/favicon.ico'
author: rosari J
paginate: 5
disqus: 'demowebsite'
locale: id_ID
lang: id_ID
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-160052565-1

# Authors
authors:
  rosari J :
    name: rosari J 
    display_name: rosari J 
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Rosari J. adalah penulis di Oktrik dengan minat besar pada dunia teknologi. Ia senang berbagi wawasan dan informasi terkini seputar perkembangan teknologi terbaru. Selain menulis, Rosari juga memiliki hobi mendalami berbagai topik terkait teknologi, menjadikannya sumber inspirasi bagi para pembacanya."

# Social
social:
  linktr: https://linktr.ee/oktrik
  facebook: https://www.facebook.com/oktrikcom/
  youtube: https://www.facebook.com/oktrikcom/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

# Include media directory
include:
  - 'media'